import {
  AlertTriangle,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  Command,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  Image,
  Laptop,
  Loader2,
  LogIn,
  LogOut,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  SunMedium,
  Trash,
  User,
  UserPlus,
  X,
  GraduationCap,
  Briefcase,
  MessageSquareHeart,
  Users,
  Bot,
  Search,
  Filter,
  Send,
  Edit3,
  BookOpenText,
  MessageCircle,
  ThumbsUp,
  ThumbsDown,
  CalendarDays,
  Link,
  Mail,
  Phone,
  MapPin,
  Building,
  Sparkles,
  Menu,
  PanelLeft,
  LayoutDashboard,
  UserCircle,
  LifeBuoy
} from 'lucide-react';

export type Icon = React.ElementType;

export const Icons = {
  logo: GraduationCap,
  dashboard: LayoutDashboard,
  profile: UserCircle,
  alumniDirectory: Users,
  mentorship: MessageSquareHeart,
  posts: BookOpenText,
  discussions: MessageCircle, // Changed from Users for differentiation
  myOpportunities: Briefcase,
  chatbot: Bot,
  help: LifeBuoy,
  login: LogIn,
  logout: LogOut,
  userPlus: UserPlus,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  helpCircle: HelpCircle,
  moon: Moon,
  sun: SunMedium,
  laptop: Laptop,
  check: Check,
  search: Search,
  filter: Filter,
  send: Send,
  edit: Edit3,
  thumbsUp: ThumbsUp,
  thumbsDown: ThumbsDown,
  calendar: CalendarDays,
  link: Link,
  mail: Mail,
  phone: Phone,
  mapPin: MapPin,
  company: Building,
  ai: Sparkles,
  menu: Menu,
  panelLeft: PanelLeft,
};
